[package]
name = "advance"
version = "0.1.0"
edition = "2018"
authors = ["notgull <jtnunley01@gmail.com>"]
rust-version = "1.36.0"
description = "IoSlice::advance() for stable targets"
license = "BSL-1.0"